package project_280;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import project_280.workouts;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author انغام
 */
public class excersices extends javax.swing.JFrame {

    /**
     * Creates new form excersice
     */
    public excersices() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        done = new javax.swing.JRadioButton();
        show = new javax.swing.JLabel();
        fav = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        vid = new javax.swing.JLabel();
        imajeClick = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        done.setBackground(new java.awt.Color(251, 255, 255));
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });
        getContentPane().add(done, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 30, 40));

        show.setBackground(new java.awt.Color(251, 255, 255));
        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_280/Screenwhitee.png"))); // NOI18N
        getContentPane().add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 90, 70));

        fav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                favMouseClicked(evt);
            }
        });
        getContentPane().add(fav, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 40, 50));

        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 40, 40));

        vid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vidMouseClicked(evt);
            }
        });
        getContentPane().add(vid, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 190, 160));

        imajeClick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_280/Screen_sport.png"))); // NOI18N
        getContentPane().add(imajeClick, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 869));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
        if (done.isSelected()) {
            JOptionPane.showMessageDialog(null, "Well done!");
        }
    }//GEN-LAST:event_doneActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        new workouts().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void favMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favMouseClicked
        JOptionPane.showMessageDialog(null, "Workout added");
    }//GEN-LAST:event_favMouseClicked

    private void vidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vidMouseClicked
        try {
            Desktop.getDesktop().browse(new URI("https://www.youtube.com/watch?v=1JdJSuyCDM4"));
        } catch (URISyntaxException ex) {
            Logger.getLogger(excersices.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(excersices.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_vidMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(excersices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(excersices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(excersices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(excersices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new excersices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JRadioButton done;
    private javax.swing.JLabel fav;
    private javax.swing.JLabel imajeClick;
    private javax.swing.JLabel show;
    private javax.swing.JLabel vid;
    // End of variables declaration//GEN-END:variables
}
