package project_280;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bayan
 */
public class meals extends javax.swing.JFrame {

    /**
     * Creates new form Profile_PersonalInfo
     */
    public meals() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        meal = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        progress = new javax.swing.JLabel();
        sport = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        picMael = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        meal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mealMouseClicked(evt);
            }
        });
        getContentPane().add(meal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 360, 130));

        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 820, 40, 30));

        progress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                progressMouseClicked(evt);
            }
        });
        getContentPane().add(progress, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 810, 40, 40));

        sport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sportMouseClicked(evt);
            }
        });
        getContentPane().add(sport, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 810, 40, 40));

        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });
        getContentPane().add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 820, 40, 30));

        picMael.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_280/Screen_Meals.png"))); // NOI18N
        picMael.setMinimumSize(new java.awt.Dimension(469, 879));
        picMael.setPreferredSize(new java.awt.Dimension(469, 879));
        getContentPane().add(picMael, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mealMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mealMouseClicked
        new mealRecepie().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mealMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void sportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sportMouseClicked
        new workouts().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sportMouseClicked

    private void progressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressMouseClicked
        new prograss().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_progressMouseClicked

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
        new profile().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_profileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(meals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(meals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(meals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(meals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new meals().setVisible(true);
            }
        });
 }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel home;
    private javax.swing.JLabel meal;
    private javax.swing.JLabel picMael;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel progress;
    private javax.swing.JLabel sport;
    // End of variables declaration//GEN-END:variables
}
