package project_280;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jana
 */
public class profile extends javax.swing.JFrame {

    /**
     * Creates new form Profile
     */
    public profile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profile = new javax.swing.JLabel();
        prograss = new javax.swing.JLabel();
        Workouts = new javax.swing.JLabel();
        Meals = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Personal_Info = new javax.swing.JButton();
        Workout_Info = new javax.swing.JButton();
        Diet_Info = new javax.swing.JButton();
        Setting = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });
        getContentPane().add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 820, 30, 20));

        prograss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prograssMouseClicked(evt);
            }
        });
        getContentPane().add(prograss, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 820, 40, 20));

        Workouts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WorkoutsMouseClicked(evt);
            }
        });
        getContentPane().add(Workouts, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 820, 30, 30));

        Meals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MealsMouseClicked(evt);
            }
        });
        getContentPane().add(Meals, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 820, 40, 30));

        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        getContentPane().add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 820, 30, 30));

        Personal_Info.setBackground(new java.awt.Color(255, 255, 255));
        Personal_Info.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Personal_Info.setForeground(new java.awt.Color(0, 51, 102));
        Personal_Info.setText("Personal information");
        Personal_Info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Personal_InfoActionPerformed(evt);
            }
        });
        getContentPane().add(Personal_Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 300, 40));

        Workout_Info.setBackground(new java.awt.Color(255, 255, 255));
        Workout_Info.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Workout_Info.setForeground(new java.awt.Color(0, 51, 102));
        Workout_Info.setText("Workout information");
        Workout_Info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Workout_InfoActionPerformed(evt);
            }
        });
        getContentPane().add(Workout_Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 300, 40));

        Diet_Info.setBackground(new java.awt.Color(255, 255, 255));
        Diet_Info.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Diet_Info.setForeground(new java.awt.Color(0, 51, 102));
        Diet_Info.setText("Diet information");
        Diet_Info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Diet_InfoActionPerformed(evt);
            }
        });
        getContentPane().add(Diet_Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 300, 40));

        Setting.setBackground(new java.awt.Color(255, 255, 255));
        Setting.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Setting.setForeground(new java.awt.Color(0, 51, 102));
        Setting.setText("Setting");
        Setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingActionPerformed(evt);
            }
        });
        getContentPane().add(Setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 300, 40));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_280/Screen_profile.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
        new profile().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_profileMouseClicked

    private void prograssMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prograssMouseClicked
        new prograss().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_prograssMouseClicked

    private void WorkoutsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WorkoutsMouseClicked
        //new Workouts().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_WorkoutsMouseClicked

    private void MealsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MealsMouseClicked
        //new Meals().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MealsMouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeMouseClicked

    private void Personal_InfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Personal_InfoActionPerformed
        new profile_PersonalInfo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Personal_InfoActionPerformed

    private void Workout_InfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Workout_InfoActionPerformed
        new profile_WorkoutInfo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Workout_InfoActionPerformed

    private void Diet_InfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Diet_InfoActionPerformed
        new profile_DietInfo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Diet_InfoActionPerformed

    private void SettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingActionPerformed
        new setting().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SettingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton Diet_Info;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Meals;
    private javax.swing.JButton Personal_Info;
    private javax.swing.JButton Setting;
    private javax.swing.JButton Workout_Info;
    private javax.swing.JLabel Workouts;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel prograss;
    // End of variables declaration//GEN-END:variables
}
