package project_280;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author jana
 */
public class profile_WorkoutInfo extends javax.swing.JFrame {

    /**
     * Creates new form Profile_WorkoutInfo
     */
    public profile_WorkoutInfo() {
        initComponents();
        this.setInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Confirm_Editing = new javax.swing.JOptionPane();
        Back = new javax.swing.JLabel();
        Athletic_level = new javax.swing.JComboBox<>();
        Athletic_level_Edit = new javax.swing.JButton();
        Avrage_time_Edit = new javax.swing.JButton();
        Sunday = new javax.swing.JCheckBox();
        Monday = new javax.swing.JCheckBox();
        Tuesday = new javax.swing.JCheckBox();
        Wednesday = new javax.swing.JCheckBox();
        Thursday = new javax.swing.JCheckBox();
        Friday = new javax.swing.JCheckBox();
        Saturday = new javax.swing.JCheckBox();
        Avrage_time = new javax.swing.JSpinner();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 34, 30, 20));

        Athletic_level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "I rarely/never exercise", "1-3 times per week", "4-5 times per week", "6-7 times per week" }));
        Athletic_level.setEnabled(false);
        Athletic_level.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Athletic_levelItemStateChanged(evt);
            }
        });
        Athletic_level.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Athletic_levelMouseClicked(evt);
            }
        });
        getContentPane().add(Athletic_level, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 120, 30));

        Athletic_level_Edit.setBackground(new java.awt.Color(255, 255, 255));
        Athletic_level_Edit.setForeground(new java.awt.Color(0, 0, 102));
        Athletic_level_Edit.setText("Edit");
        Athletic_level_Edit.setEnabled(false);
        Athletic_level_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Athletic_level_EditActionPerformed(evt);
            }
        });
        getContentPane().add(Athletic_level_Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 60, 20));

        Avrage_time_Edit.setBackground(new java.awt.Color(255, 255, 255));
        Avrage_time_Edit.setForeground(new java.awt.Color(0, 0, 102));
        Avrage_time_Edit.setText("Edit");
        Avrage_time_Edit.setEnabled(false);
        Avrage_time_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Avrage_time_EditActionPerformed(evt);
            }
        });
        getContentPane().add(Avrage_time_Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 60, 20));

        Sunday.setBackground(new java.awt.Color(255, 255, 255));
        Sunday.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Sunday.setEnabled(false);
        Sunday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SundayMouseClicked(evt);
            }
        });
        getContentPane().add(Sunday, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 20, 20));

        Monday.setBackground(new java.awt.Color(255, 255, 255));
        Monday.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Monday.setEnabled(false);
        Monday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MondayMouseClicked(evt);
            }
        });
        Monday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_days(evt);
            }
        });
        getContentPane().add(Monday, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 20, 20));

        Tuesday.setBackground(new java.awt.Color(255, 255, 255));
        Tuesday.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Tuesday.setEnabled(false);
        Tuesday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TuesdayMouseClicked(evt);
            }
        });
        getContentPane().add(Tuesday, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 20, 20));

        Wednesday.setBackground(new java.awt.Color(255, 255, 255));
        Wednesday.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Wednesday.setEnabled(false);
        Wednesday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WednesdayMouseClicked(evt);
            }
        });
        getContentPane().add(Wednesday, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 405, 20, 20));

        Thursday.setBackground(new java.awt.Color(255, 255, 255));
        Thursday.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Thursday.setEnabled(false);
        Thursday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThursdayMouseClicked(evt);
            }
        });
        getContentPane().add(Thursday, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 405, 20, 20));

        Friday.setBackground(new java.awt.Color(255, 255, 255));
        Friday.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Friday.setEnabled(false);
        Friday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FridayMouseClicked(evt);
            }
        });
        getContentPane().add(Friday, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 405, 20, 20));

        Saturday.setBackground(new java.awt.Color(255, 255, 255));
        Saturday.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Saturday.setEnabled(false);
        Saturday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaturdayMouseClicked(evt);
            }
        });
        getContentPane().add(Saturday, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 20, 20));

        Avrage_time.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Avrage_time.setModel(new javax.swing.SpinnerNumberModel(1, 1, 7, 1));
        Avrage_time.setEnabled(false);
        Avrage_time.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Avrage_timeStateChanged(evt);
            }
        });
        Avrage_time.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Avrage_timeMouseClicked(evt);
            }
        });
        getContentPane().add(Avrage_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 40, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_280/Screen_profile_workoutInfo.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Athletic_level_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Athletic_level_EditActionPerformed
        int result = Confirm_Editing.showOptionDialog(
                this,
                "Are You Sure?",
                "Confirm",
                Confirm_Editing.YES_NO_OPTION,
                Confirm_Editing.QUESTION_MESSAGE, null, null, null);

        if (result == Confirm_Editing.YES_OPTION) {
            String newAthletic_level = Athletic_level.getItemAt(Athletic_level.getSelectedIndex());
            profile_WorkoutInfo n = new profile_WorkoutInfo();
            n.Athletic_level.setSelectedItem(newAthletic_level);
            switch (Athletic_level.getSelectedIndex()) {
                case 0:
                    step5.reraly_never.setSelected(true);
                    break;
                case 1:
                    step5.Times1_3.setSelected(true);
                    break;
                case 2:
                    step5.Times4_5.setSelected(true);
                    break;
                case 3:
                    step5.Times6_7.setSelected(true);
                    break;
            }
            n.setVisible(true);
            this.dispose();
        } else {
            Athletic_level.setEnabled(false);
            Athletic_level_Edit.setEnabled(false);
        }
    }//GEN-LAST:event_Athletic_level_EditActionPerformed

    private void Avrage_time_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Avrage_time_EditActionPerformed
        int result = Confirm_Editing.showOptionDialog(
                this,
                "Are You Sure?",
                "Confirm",
                Confirm_Editing.YES_NO_OPTION,
                Confirm_Editing.QUESTION_MESSAGE, null, null, null);

        if (result == Confirm_Editing.YES_OPTION) {
            int newAvrage_time = (int) Avrage_time.getValue();
            profile_WorkoutInfo n = new profile_WorkoutInfo();
            n.setVisible(true);
            n.Avrage_time.setValue(newAvrage_time);
            this.dispose();
        } else {
            Avrage_time.setEnabled(false);
            Avrage_time_Edit.setEnabled(false);
        }
    }//GEN-LAST:event_Avrage_time_EditActionPerformed

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        new profile().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackMouseClicked

    private void Athletic_levelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Athletic_levelItemStateChanged
        Athletic_level_Edit.setEnabled(true);
    }//GEN-LAST:event_Athletic_levelItemStateChanged

    private void Athletic_levelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Athletic_levelMouseClicked
        if (Athletic_level.isEnabled() == false) {
            Athletic_level.setEnabled(true);
        }
    }//GEN-LAST:event_Athletic_levelMouseClicked

    private void Avrage_timeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Avrage_timeStateChanged
        if (Avrage_time.isEnabled()) {
            Avrage_time_Edit.setEnabled(true);
        }
    }//GEN-LAST:event_Avrage_timeStateChanged

    private void SundayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SundayMouseClicked
        if (Sunday.isEnabled() == false) {
            Sunday.setEnabled(true);
        }
    }//GEN-LAST:event_SundayMouseClicked

    private void MondayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MondayMouseClicked
        if (Monday.isEnabled() == false) {
            Monday.setEnabled(true);
        }
    }//GEN-LAST:event_MondayMouseClicked

    private void TuesdayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TuesdayMouseClicked
        if (Tuesday.isEnabled() == false) {
            Tuesday.setEnabled(true);
        }
    }//GEN-LAST:event_TuesdayMouseClicked

    private void WednesdayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WednesdayMouseClicked
        if (Wednesday.isEnabled() == false) {
            Wednesday.setEnabled(true);
        }
    }//GEN-LAST:event_WednesdayMouseClicked

    private void ThursdayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThursdayMouseClicked
        if (Thursday.isEnabled() == false) {
            Thursday.setEnabled(true);
        }
    }//GEN-LAST:event_ThursdayMouseClicked

    private void FridayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FridayMouseClicked
        if (Friday.isEnabled() == false) {
            Friday.setEnabled(true);
        }
    }//GEN-LAST:event_FridayMouseClicked

    private void SaturdayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaturdayMouseClicked
        if (Saturday.isEnabled() == false) {
            Saturday.setEnabled(true);
        }
    }//GEN-LAST:event_SaturdayMouseClicked

    private void Edit_days(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_days
        boolean[] newdays = new boolean[7];
        newdays[0] = Sunday.isSelected();
        newdays[1] = Monday.isSelected();
        newdays[2] = Tuesday.isSelected();
        newdays[3] = Wednesday.isSelected();
        newdays[4] = Thursday.isSelected();
        newdays[5] = Friday.isSelected();
        newdays[6] = Saturday.isSelected();
        profile_WorkoutInfo n = new profile_WorkoutInfo();
        n.setVisible(true);
        n.Sunday.setSelected(newdays[0]);
        n.Monday.setSelected(newdays[1]);
        n.Tuesday.setSelected(newdays[2]);
        n.Wednesday.setSelected(newdays[3]);
        n.Thursday.setSelected(newdays[4]);
        n.Friday.setSelected(newdays[5]);
        n.Saturday.setSelected(newdays[6]);
        this.dispose();
    }//GEN-LAST:event_Edit_days

    private void Avrage_timeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Avrage_timeMouseClicked
        Avrage_time.setEnabled(true);
    }//GEN-LAST:event_Avrage_timeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profile_WorkoutInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profile_WorkoutInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profile_WorkoutInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profile_WorkoutInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                profile_WorkoutInfo frame = new profile_WorkoutInfo();
                frame.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> Athletic_level;
    private javax.swing.JButton Athletic_level_Edit;
    public static javax.swing.JSpinner Avrage_time;
    private javax.swing.JButton Avrage_time_Edit;
    private javax.swing.JLabel Back;
    private javax.swing.JLabel Background;
    private javax.swing.JOptionPane Confirm_Editing;
    public static javax.swing.JCheckBox Friday;
    public static javax.swing.JCheckBox Monday;
    public static javax.swing.JCheckBox Saturday;
    public static javax.swing.JCheckBox Sunday;
    public static javax.swing.JCheckBox Thursday;
    public static javax.swing.JCheckBox Tuesday;
    public static javax.swing.JCheckBox Wednesday;
    // End of variables declaration//GEN-END:variables

    public static void setInfo() {
        if (welcome.here.equals("signUp")) {
            if (step5.reraly_never.isSelected()) {
                Athletic_level.setSelectedIndex(0);
            } else if (step5.Times1_3.isSelected()) {
                Athletic_level.setSelectedIndex(1);
            } else if (step5.Times4_5.isSelected()) {
                Athletic_level.setSelectedIndex(2);
            } else if (step5.Times6_7.isSelected()) {
                Athletic_level.setSelectedIndex(3);
            }

            //workout days and avrage time
            int count = 0;
            if (step6.Sunday.isSelected()) {
                count++;
                Sunday.setSelected(true);
            }
            if (step6.Monday.isSelected()) {
                count++;
                Monday.setSelected(true);
            }
            if (step6.Tuesday.isSelected()) {
                count++;
                Tuesday.setSelected(true);
            }
            if (step6.Wednesday.isSelected()) {
                count++;
                Wednesday.setSelected(true);
            }
            if (step6.Thursday.isSelected()) {
                count++;
                Thursday.setSelected(true);
            }
            if (step6.Friday.isSelected()) {
                count++;
                Friday.setSelected(true);
            }
            if (step6.Saturday.isSelected()) {
                count++;
                Saturday.setSelected(true);
            }
            Avrage_time.setValue(count);
        } else if (welcome.here.equals("logIn")) {
            Athletic_level.setSelectedIndex(0);
            //workout days and avrage time
            Sunday.setSelected(true);
            Tuesday.setSelected(true);
            Friday.setSelected(true);
            Avrage_time.setValue(3);
        } else if (welcome.here.equals("")) {
            Athletic_level.setSelectedIndex(0);
            //workout days and avrage time
            Sunday.setSelected(true);
            Tuesday.setSelected(true);
            Friday.setSelected(true);
            Avrage_time.setValue(3);
        }
    }
}
