package project_280;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jana
 */
public class prograss extends javax.swing.JFrame {

    /**
     * Creates new form Prograss
     */
    public prograss() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Confirm_Editing = new javax.swing.JOptionPane();
        Update_weight = new javax.swing.JTextField();
        ERROR = new javax.swing.JLabel();
        prograss_Weight = new javax.swing.JSlider();
        profile = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Meals = new javax.swing.JLabel();
        Workouts = new javax.swing.JLabel();
        prograss = new javax.swing.JLabel();
        Backgroud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Update_weight.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Update_weightCaretUpdate(evt);
            }
        });
        getContentPane().add(Update_weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 192, 70, 30));

        ERROR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ERROR.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(ERROR, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 240, 20));

        prograss_Weight.setBackground(new java.awt.Color(255, 255, 255));
        prograss_Weight.setMaximum(52);
        prograss_Weight.setMinimum(24);
        prograss_Weight.setValue(30);
        prograss_Weight.setEnabled(false);
        prograss_Weight.setInverted(true);
        getContentPane().add(prograss_Weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 220, 40));

        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });
        getContentPane().add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 820, 30, 20));

        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        getContentPane().add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 820, 30, 30));

        Meals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MealsMouseClicked(evt);
            }
        });
        getContentPane().add(Meals, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 820, 40, 30));

        Workouts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WorkoutsMouseClicked(evt);
            }
        });
        getContentPane().add(Workouts, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 820, 30, 30));

        prograss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prograssMouseClicked(evt);
            }
        });
        getContentPane().add(prograss, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 820, 40, 20));

        Backgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_280/Screen_Prograss.png"))); // NOI18N
        getContentPane().add(Backgroud, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Update_weightCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Update_weightCaretUpdate
        
        if (Update_weight.getText().length() == 0) {
            ERROR.setText("");
        }
        else if (Update_weight.getText().matches("\\d+")){
            int weight = Integer.parseInt(Update_weight.getText());
            prograss_Weight.setValue(weight);
            ERROR.setText("");
        }
        else {
            ERROR.setText("Please enter numbers only.");
        }
    }//GEN-LAST:event_Update_weightCaretUpdate

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
        new profile().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_profileMouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeMouseClicked

    private void MealsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MealsMouseClicked
        new meals().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MealsMouseClicked

    private void WorkoutsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WorkoutsMouseClicked
        new workouts().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_WorkoutsMouseClicked

    private void prograssMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prograssMouseClicked
        new prograss().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_prograssMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prograss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prograss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prograss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prograss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prograss().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backgroud;
    private javax.swing.JOptionPane Confirm_Editing;
    private javax.swing.JLabel ERROR;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Meals;
    private javax.swing.JTextField Update_weight;
    private javax.swing.JLabel Workouts;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel prograss;
    private javax.swing.JSlider prograss_Weight;
    // End of variables declaration//GEN-END:variables

}
