package project_280;

/**
 * @author Galawi
 */
public class reset extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public reset() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JLabel();
        front = new javax.swing.JLabel();
        byPhone = new javax.swing.JLabel();
        byEmail = new javax.swing.JLabel();
        pic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 60, 50));

        front.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_280/Screenwhitee.png"))); // NOI18N
        getContentPane().add(front, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 750, 130, 100));

        byPhone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                byPhoneMouseClicked(evt);
            }
        });
        getContentPane().add(byPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 310, 80));

        byEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                byEmailMouseClicked(evt);
            }
        });
        getContentPane().add(byEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 310, 80));

        pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_280/ScreenReset.png"))); // NOI18N
        getContentPane().add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 400, 860));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        new logIn().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void byPhoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_byPhoneMouseClicked
        new resetByPhone().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_byPhoneMouseClicked

    private void byEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_byEmailMouseClicked
        new resetByEmail().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_byEmailMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reset().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel byEmail;
    private javax.swing.JLabel byPhone;
    private javax.swing.JLabel front;
    private javax.swing.JLabel pic;
    // End of variables declaration//GEN-END:variables
}
