package project_280;

import javax.swing.JOptionPane;

/**
 *
 * @author Galawi
 */
public class resetPassword extends javax.swing.JFrame {

    /**
     * Creates new form resetPassword
     */
    public resetPassword() {
        initComponents();
        good.setVisible(false);
        Strong.setVisible(false);
        week.setVisible(false);
        note.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JLabel();
        white = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        confirm = new javax.swing.JPasswordField();
        Strong = new javax.swing.JLabel();
        note = new javax.swing.JLabel();
        week = new javax.swing.JLabel();
        good = new javax.swing.JLabel();
        Reset = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 60, 50));

        white.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_280/Screenwhitee.png"))); // NOI18N
        getContentPane().add(white, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 620, 240, 60));

        password.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                passwordCaretUpdate(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 130, -1));
        getContentPane().add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 130, -1));

        Strong.setForeground(new java.awt.Color(51, 204, 0));
        Strong.setText("Strong");
        Strong.setToolTipText("");
        getContentPane().add(Strong, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 60, -1));

        note.setForeground(new java.awt.Color(204, 0, 0));
        note.setText("Password do not match");
        note.setToolTipText("");
        getContentPane().add(note, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, -1, -1));

        week.setForeground(new java.awt.Color(204, 0, 0));
        week.setText(" weak");
        week.setToolTipText("");
        week.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(week, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 50, -1));

        good.setForeground(new java.awt.Color(255, 204, 51));
        good.setText("good");
        good.setToolTipText("");
        getContentPane().add(good, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 40, -1));

        Reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetMouseClicked(evt);
            }
        });
        getContentPane().add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 310, 60));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_280/ScreenresetPassword.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        new reset().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void passwordCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_passwordCaretUpdate
        if (password.getText().length() <= 3) {
            week.setVisible(true);
            good.setVisible(false);
            Strong.setVisible(false);
        }
        if (password.getText().length() > 3 && password.getText().length() <= 8) {
            good.setVisible(true);
            week.setVisible(false);
            Strong.setVisible(false);
        }
        if (password.getText().length() > 8) {
            Strong.setVisible(true);
            week.setVisible(false);
            good.setVisible(false);
        }
    }//GEN-LAST:event_passwordCaretUpdate

    private void ResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetMouseClicked
        if (password.getText().isEmpty() || confirm.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.");
        } else if (password.getText().equals(confirm.getText())) {
            white.setVisible(false);
            note.setVisible(false);
        } else {
            note.setVisible(true);
        }
    }//GEN-LAST:event_ResetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resetPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Reset;
    private javax.swing.JLabel Strong;
    private javax.swing.JLabel back;
    private javax.swing.JLabel background;
    private javax.swing.JPasswordField confirm;
    private javax.swing.JLabel good;
    private javax.swing.JLabel note;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel week;
    private javax.swing.JLabel white;
    // End of variables declaration//GEN-END:variables
}
