package project_280;

import javax.swing.JOptionPane;

/**
 * @author Galawi
 */
public class resetByPhone extends javax.swing.JFrame {

    /**
     * Creates new form resetByPhone
     */
    public resetByPhone() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        white = new javax.swing.JLabel();
        send = new javax.swing.JLabel();
        piv = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 28, 60, 50));
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 266, 290, 40));

        white.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_280/Screenwhitee.png"))); // NOI18N
        getContentPane().add(white, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 545, 240, 60));

        send.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendMouseClicked(evt);
            }
        });
        getContentPane().add(send, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 310, 50));

        piv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_280/ScreenResetByPhone.png"))); // NOI18N
        getContentPane().add(piv, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        new reset().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void sendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMouseClicked
        if (phone.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill the field.");
        } else if (!phone.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Wrong phone number it must be Digits");
        } else if (phone.getText().length() != 10) {
            JOptionPane.showMessageDialog(this, "Wrong phone number it must be 10 Digits");
        } else {
            white.setVisible(false);
            new logIn().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_sendMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resetByPhone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resetByPhone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resetByPhone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resetByPhone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resetByPhone().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel piv;
    private javax.swing.JLabel send;
    private javax.swing.JLabel white;
    // End of variables declaration//GEN-END:variables
}
