package project_280;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author انغام
 */
public class step4 extends javax.swing.JFrame {

    /**
     * Creates new form step4
     */
    public step4() {
        initComponents();

        Under.setVisible(false);
        Hint.setVisible(false);
        Invalid.setVisible(false);
        Above.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        weight = new javax.swing.JTextField();
        next = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Under = new javax.swing.JLabel();
        Invalid = new javax.swing.JLabel();
        Hint = new javax.swing.JLabel();
        Above = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightActionPerformed(evt);
            }
        });
        getContentPane().add(weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 80, 40));

        next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextMouseClicked(evt);
            }
        });
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 720, 130, 110));

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 80, 50));

        Under.setForeground(new java.awt.Color(255, 51, 0));
        Under.setText("Complate your entery");
        getContentPane().add(Under, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 140, 20));

        Invalid.setForeground(new java.awt.Color(255, 51, 51));
        Invalid.setText("Invalid weight");
        getContentPane().add(Invalid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 110, -1));

        Hint.setForeground(new java.awt.Color(255, 51, 0));
        Hint.setText("Hint : must be 2 Digit");
        getContentPane().add(Hint, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 160, 30));

        Above.setForeground(new java.awt.Color(255, 51, 0));
        Above.setText("cannot enter more than 3 digit to enter");
        getContentPane().add(Above, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 250, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_280/Screen4.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        new step3().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseClicked
        if (weight.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill the field.");
        } else if (!weight.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Wrong! It must be Digits");
        } else if (weight.getText().length() < 2) {
            Invalid.setVisible(true);
            Under.setVisible(true);
            Hint.setVisible(true);
        } else if (weight.getText().length() > 3) {
            Invalid.setVisible(true);
            Above.setVisible(true);
        } else {
            step5 a = new step5();
            a.setVisible(true);
            this.setVisible(false);

        }

    }//GEN-LAST:event_nextMouseClicked

    private void weightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_weightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(step4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(step4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(step4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(step4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new step4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Above;
    private javax.swing.JLabel Hint;
    private javax.swing.JLabel Invalid;
    private javax.swing.JLabel Under;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel next;
    public static javax.swing.JTextField weight;
    // End of variables declaration//GEN-END:variables
}
