package project_280;

/**
 * @author انغام
 */
public class step1 extends javax.swing.JFrame {

    /**
     * Creates new form Step1
     */
    public step1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JLabel();
        lose = new javax.swing.JLabel();
        gain = new javax.swing.JLabel();
        getFitter = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 80));

        lose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loseMouseClicked(evt);
            }
        });
        getContentPane().add(lose, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 310, 80));

        gain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gainMouseClicked(evt);
            }
        });
        getContentPane().add(gain, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 310, 80));

        getFitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getFitterMouseClicked(evt);
            }
        });
        getContentPane().add(getFitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 310, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_280/Screen1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 860));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        new welcome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void loseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loseMouseClicked
        new step2().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loseMouseClicked

    private void gainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gainMouseClicked
        new step2().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gainMouseClicked

    private void getFitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getFitterMouseClicked
        new step2().setVisible(true);
        this.dispose();       
    }//GEN-LAST:event_getFitterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(step1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(step1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(step1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(step1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new step1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel gain;
    private javax.swing.JLabel getFitter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lose;
    // End of variables declaration//GEN-END:variables
}
