package project_280;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author انغام
 */
public class step6 extends javax.swing.JFrame {

    /**
     * Creates new form step6
     */
    public step6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Monday = new javax.swing.JCheckBox();
        Tuesday = new javax.swing.JCheckBox();
        Friday = new javax.swing.JCheckBox();
        Thursday = new javax.swing.JCheckBox();
        Wednesday = new javax.swing.JCheckBox();
        Sunday = new javax.swing.JCheckBox();
        Saturday = new javax.swing.JCheckBox();
        front = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        pic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Monday.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Monday, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 251, -1, -1));

        Tuesday.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Tuesday, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 251, -1, -1));

        Friday.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Friday, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 20, 30));

        Thursday.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Thursday, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 20, -1));

        Wednesday.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Wednesday, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 20, 20));

        Sunday.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Sunday, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 251, -1, -1));

        Saturday.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Saturday, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, -1, -1));

        front.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                frontMouseClicked(evt);
            }
        });
        getContentPane().add(front, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 740, 100, 90));

        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 70, 70));

        pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_280/Screen_Login _19.png"))); // NOI18N
        getContentPane().add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void frontMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frontMouseClicked
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_frontMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        new step5().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(step6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(step6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(step6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(step6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new step6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JCheckBox Friday;
    public static javax.swing.JCheckBox Monday;
    public static javax.swing.JCheckBox Saturday;
    public static javax.swing.JCheckBox Sunday;
    public static javax.swing.JCheckBox Thursday;
    public static javax.swing.JCheckBox Tuesday;
    public static javax.swing.JCheckBox Wednesday;
    private javax.swing.JLabel back;
    private javax.swing.JLabel front;
    private javax.swing.JLabel pic;
    // End of variables declaration//GEN-END:variables
}
